"""Add percent change to spiro

Revision ID: 7a1c1908f800
Revises: d7504288efe3
Create Date: 2020-01-20 11:36:21.819025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a1c1908f800'
down_revision = 'd7504288efe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spirometry', sa.Column('fev1_percent_change', sa.Float(), nullable=True))
    op.add_column('spirometry', sa.Column('fev1_pred', sa.Float(), nullable=True))
    op.add_column('spirometry', sa.Column('fvc_percent_change', sa.Float(), nullable=True))
    op.add_column('spirometry', sa.Column('fvc_pred', sa.Float(), nullable=True))
    op.drop_column('spirometry', 'fvc_pre_pred')
    op.drop_column('spirometry', 'fev1_pre_pred')
    op.drop_column('spirometry', 'fvc_post_pred')
    op.drop_column('spirometry', 'fev1_post_pred')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spirometry', sa.Column('fev1_post_pred', sa.FLOAT(), nullable=True))
    op.add_column('spirometry', sa.Column('fvc_post_pred', sa.FLOAT(), nullable=True))
    op.add_column('spirometry', sa.Column('fev1_pre_pred', sa.FLOAT(), nullable=True))
    op.add_column('spirometry', sa.Column('fvc_pre_pred', sa.FLOAT(), nullable=True))
    op.drop_column('spirometry', 'fvc_pred')
    op.drop_column('spirometry', 'fvc_percent_change')
    op.drop_column('spirometry', 'fev1_pred')
    op.drop_column('spirometry', 'fev1_percent_change')
    # ### end Alembic commands ###
