"""Initial db

Revision ID: 99340e0b68af
Revises: 
Create Date: 2020-01-20 10:19:54.913944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99340e0b68af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=100), nullable=True),
    sa.Column('lname', sa.String(length=100), nullable=True),
    sa.Column('rxr', sa.String(length=10), nullable=True),
    sa.Column('nhs', sa.String(length=15), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rxr')
    )
    op.create_table('spirometry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('study_date', sa.Date(), nullable=True),
    sa.Column('fev1_pre', sa.Float(), nullable=True),
    sa.Column('fev1_pre_pred', sa.Float(), nullable=True),
    sa.Column('fev1_pre_percent_pred', sa.Float(), nullable=True),
    sa.Column('fev1_pre_SR', sa.Float(), nullable=True),
    sa.Column('fvc_pre', sa.Float(), nullable=True),
    sa.Column('fvc_pre_pred', sa.Float(), nullable=True),
    sa.Column('fvc_pre_percent_pred', sa.Float(), nullable=True),
    sa.Column('fvc_pre_SR', sa.Float(), nullable=True),
    sa.Column('fev1_post', sa.Float(), nullable=True),
    sa.Column('fev1_post_pred', sa.Float(), nullable=True),
    sa.Column('fev1_post_percent_pred', sa.Float(), nullable=True),
    sa.Column('fev1_post_SR', sa.Float(), nullable=True),
    sa.Column('fvc_post', sa.Float(), nullable=True),
    sa.Column('fvc_post_pred', sa.Float(), nullable=True),
    sa.Column('fvc_post_percent_pred', sa.Float(), nullable=True),
    sa.Column('fvc_post_SR', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lungfunc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('spiro_id', sa.Integer(), nullable=True),
    sa.Column('study_date', sa.Date(), nullable=True),
    sa.Column('tlco', sa.Float(), nullable=True),
    sa.Column('tlco_pred', sa.Float(), nullable=True),
    sa.Column('tlco_percent_pred', sa.Float(), nullable=True),
    sa.Column('tlco_SR', sa.Float(), nullable=True),
    sa.Column('vasb', sa.Float(), nullable=True),
    sa.Column('vasb_pred', sa.Float(), nullable=True),
    sa.Column('vasb_percent_pred', sa.Float(), nullable=True),
    sa.Column('kco', sa.Float(), nullable=True),
    sa.Column('kco_pred', sa.Float(), nullable=True),
    sa.Column('kco_percent_pred', sa.Float(), nullable=True),
    sa.Column('frc', sa.Float(), nullable=True),
    sa.Column('frc_pred', sa.Float(), nullable=True),
    sa.Column('frc_percent_pred', sa.Float(), nullable=True),
    sa.Column('frc_SR', sa.Float(), nullable=True),
    sa.Column('vc', sa.Float(), nullable=True),
    sa.Column('vc_pred', sa.Float(), nullable=True),
    sa.Column('vc_percent_pred', sa.Float(), nullable=True),
    sa.Column('vc_SR', sa.Float(), nullable=True),
    sa.Column('tlc', sa.Float(), nullable=True),
    sa.Column('tlc_pred', sa.Float(), nullable=True),
    sa.Column('tlc_percent_pred', sa.Float(), nullable=True),
    sa.Column('tlc_SR', sa.Float(), nullable=True),
    sa.Column('rv', sa.Float(), nullable=True),
    sa.Column('rv_pred', sa.Float(), nullable=True),
    sa.Column('rv_percent_pred', sa.Float(), nullable=True),
    sa.Column('rv_SR', sa.Float(), nullable=True),
    sa.Column('tlcrv', sa.Float(), nullable=True),
    sa.Column('tlcrv_pred', sa.Float(), nullable=True),
    sa.Column('tlcrv_percent_pred', sa.Float(), nullable=True),
    sa.Column('tlcrv_SR', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['spiro_id'], ['spirometry.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lungfunc')
    op.drop_table('spirometry')
    op.drop_table('patient')
    # ### end Alembic commands ###
